export const SequenceMarketplace_V1_ABI = [
  {
    inputs: [{ internalType: 'address', name: '_owner', type: 'address' }],
    stateMutability: 'nonpayable',
    type: 'constructor',
  },
  { inputs: [], name: 'InvalidAdditionalFees', type: 'error' },
  { inputs: [], name: 'InvalidBatchRequest', type: 'error' },
  { inputs: [], name: 'InvalidCurrency', type: 'error' },
  {
    inputs: [
      { internalType: 'address', name: 'currency', type: 'address' },
      { internalType: 'uint256', name: 'quantity', type: 'uint256' },
      { internalType: 'address', name: 'owner', type: 'address' },
    ],
    name: 'InvalidCurrencyApproval',
    type: 'error',
  },
  { inputs: [], name: 'InvalidExpiry', type: 'error' },
  { inputs: [], name: 'InvalidPrice', type: 'error' },
  { inputs: [], name: 'InvalidQuantity', type: 'error' },
  {
    inputs: [{ internalType: 'uint256', name: 'requestId', type: 'uint256' }],
    name: 'InvalidRequestId',
    type: 'error',
  },
  { inputs: [], name: 'InvalidRoyalty', type: 'error' },
  {
    inputs: [
      { internalType: 'address', name: 'tokenContract', type: 'address' },
      { internalType: 'uint256', name: 'tokenId', type: 'uint256' },
      { internalType: 'uint256', name: 'quantity', type: 'uint256' },
      { internalType: 'address', name: 'owner', type: 'address' },
    ],
    name: 'InvalidTokenApproval',
    type: 'error',
  },
  {
    inputs: [
      { internalType: 'address', name: 'contractAddress', type: 'address' },
      { internalType: 'bytes4', name: 'interfaceId', type: 'bytes4' },
    ],
    name: 'UnsupportedContractInterface',
    type: 'error',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: 'address',
        name: 'tokenContract',
        type: 'address',
      },
      {
        indexed: false,
        internalType: 'address',
        name: 'recipient',
        type: 'address',
      },
      { indexed: false, internalType: 'uint96', name: 'fee', type: 'uint96' },
    ],
    name: 'CustomRoyaltyChanged',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: 'address',
        name: 'previousOwner',
        type: 'address',
      },
      {
        indexed: true,
        internalType: 'address',
        name: 'newOwner',
        type: 'address',
      },
    ],
    name: 'OwnershipTransferred',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: 'uint256',
        name: 'requestId',
        type: 'uint256',
      },
      {
        indexed: true,
        internalType: 'address',
        name: 'buyer',
        type: 'address',
      },
      {
        indexed: true,
        internalType: 'address',
        name: 'tokenContract',
        type: 'address',
      },
      {
        indexed: false,
        internalType: 'address',
        name: 'receiver',
        type: 'address',
      },
      {
        indexed: false,
        internalType: 'uint256',
        name: 'quantity',
        type: 'uint256',
      },
      {
        indexed: false,
        internalType: 'uint256',
        name: 'quantityRemaining',
        type: 'uint256',
      },
    ],
    name: 'RequestAccepted',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: 'uint256',
        name: 'requestId',
        type: 'uint256',
      },
      {
        indexed: true,
        internalType: 'address',
        name: 'tokenContract',
        type: 'address',
      },
    ],
    name: 'RequestCancelled',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: 'uint256',
        name: 'requestId',
        type: 'uint256',
      },
      {
        indexed: true,
        internalType: 'address',
        name: 'creator',
        type: 'address',
      },
      {
        indexed: true,
        internalType: 'address',
        name: 'tokenContract',
        type: 'address',
      },
      {
        indexed: false,
        internalType: 'uint256',
        name: 'tokenId',
        type: 'uint256',
      },
      { indexed: false, internalType: 'bool', name: 'isListing', type: 'bool' },
      {
        indexed: false,
        internalType: 'uint256',
        name: 'quantity',
        type: 'uint256',
      },
      {
        indexed: false,
        internalType: 'address',
        name: 'currency',
        type: 'address',
      },
      {
        indexed: false,
        internalType: 'uint256',
        name: 'pricePerToken',
        type: 'uint256',
      },
      {
        indexed: false,
        internalType: 'uint256',
        name: 'expiry',
        type: 'uint256',
      },
    ],
    name: 'RequestCreated',
    type: 'event',
  },
  {
    inputs: [
      { internalType: 'uint256', name: 'requestId', type: 'uint256' },
      { internalType: 'uint256', name: 'quantity', type: 'uint256' },
      { internalType: 'address', name: 'receiver', type: 'address' },
      { internalType: 'uint256[]', name: 'additionalFees', type: 'uint256[]' },
      {
        internalType: 'address[]',
        name: 'additionalFeeReceivers',
        type: 'address[]',
      },
    ],
    name: 'acceptRequest',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'uint256[]', name: 'requestIds', type: 'uint256[]' },
      { internalType: 'uint256[]', name: 'quantities', type: 'uint256[]' },
      { internalType: 'address[]', name: 'receivers', type: 'address[]' },
      { internalType: 'uint256[]', name: 'additionalFees', type: 'uint256[]' },
      {
        internalType: 'address[]',
        name: 'additionalFeeReceivers',
        type: 'address[]',
      },
    ],
    name: 'acceptRequestBatch',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: 'requestId', type: 'uint256' }],
    name: 'cancelRequest',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'uint256[]', name: 'requestIds', type: 'uint256[]' },
    ],
    name: 'cancelRequestBatch',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      {
        components: [
          { internalType: 'bool', name: 'isListing', type: 'bool' },
          { internalType: 'bool', name: 'isERC1155', type: 'bool' },
          { internalType: 'address', name: 'tokenContract', type: 'address' },
          { internalType: 'uint256', name: 'tokenId', type: 'uint256' },
          { internalType: 'uint256', name: 'quantity', type: 'uint256' },
          { internalType: 'uint96', name: 'expiry', type: 'uint96' },
          { internalType: 'address', name: 'currency', type: 'address' },
          { internalType: 'uint256', name: 'pricePerToken', type: 'uint256' },
        ],
        internalType: 'struct ISequenceMarketStorage.RequestParams',
        name: 'request',
        type: 'tuple',
      },
    ],
    name: 'createRequest',
    outputs: [{ internalType: 'uint256', name: 'requestId', type: 'uint256' }],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      {
        components: [
          { internalType: 'bool', name: 'isListing', type: 'bool' },
          { internalType: 'bool', name: 'isERC1155', type: 'bool' },
          { internalType: 'address', name: 'tokenContract', type: 'address' },
          { internalType: 'uint256', name: 'tokenId', type: 'uint256' },
          { internalType: 'uint256', name: 'quantity', type: 'uint256' },
          { internalType: 'uint96', name: 'expiry', type: 'uint96' },
          { internalType: 'address', name: 'currency', type: 'address' },
          { internalType: 'uint256', name: 'pricePerToken', type: 'uint256' },
        ],
        internalType: 'struct ISequenceMarketStorage.RequestParams[]',
        name: 'requests',
        type: 'tuple[]',
      },
    ],
    name: 'createRequestBatch',
    outputs: [
      { internalType: 'uint256[]', name: 'requestIds', type: 'uint256[]' },
    ],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: '', type: 'address' }],
    name: 'customRoyalties',
    outputs: [
      { internalType: 'address', name: 'recipient', type: 'address' },
      { internalType: 'uint96', name: 'fee', type: 'uint96' },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: 'requestId', type: 'uint256' }],
    name: 'getRequest',
    outputs: [
      {
        components: [
          { internalType: 'address', name: 'creator', type: 'address' },
          { internalType: 'bool', name: 'isListing', type: 'bool' },
          { internalType: 'bool', name: 'isERC1155', type: 'bool' },
          { internalType: 'address', name: 'tokenContract', type: 'address' },
          { internalType: 'uint256', name: 'tokenId', type: 'uint256' },
          { internalType: 'uint256', name: 'quantity', type: 'uint256' },
          { internalType: 'uint96', name: 'expiry', type: 'uint96' },
          { internalType: 'address', name: 'currency', type: 'address' },
          { internalType: 'uint256', name: 'pricePerToken', type: 'uint256' },
        ],
        internalType: 'struct ISequenceMarketStorage.Request',
        name: 'request',
        type: 'tuple',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'uint256[]', name: 'requestIds', type: 'uint256[]' },
    ],
    name: 'getRequestBatch',
    outputs: [
      {
        components: [
          { internalType: 'address', name: 'creator', type: 'address' },
          { internalType: 'bool', name: 'isListing', type: 'bool' },
          { internalType: 'bool', name: 'isERC1155', type: 'bool' },
          { internalType: 'address', name: 'tokenContract', type: 'address' },
          { internalType: 'uint256', name: 'tokenId', type: 'uint256' },
          { internalType: 'uint256', name: 'quantity', type: 'uint256' },
          { internalType: 'uint96', name: 'expiry', type: 'uint96' },
          { internalType: 'address', name: 'currency', type: 'address' },
          { internalType: 'uint256', name: 'pricePerToken', type: 'uint256' },
        ],
        internalType: 'struct ISequenceMarketStorage.Request[]',
        name: 'requests',
        type: 'tuple[]',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: 'tokenContract', type: 'address' },
      { internalType: 'uint256', name: 'tokenId', type: 'uint256' },
      { internalType: 'uint256', name: 'cost', type: 'uint256' },
    ],
    name: 'getRoyaltyInfo',
    outputs: [
      { internalType: 'address', name: 'recipient', type: 'address' },
      { internalType: 'uint256', name: 'royalty', type: 'uint256' },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'uint256', name: 'requestId', type: 'uint256' },
      { internalType: 'uint256', name: 'quantity', type: 'uint256' },
    ],
    name: 'isRequestValid',
    outputs: [
      { internalType: 'bool', name: 'valid', type: 'bool' },
      {
        components: [
          { internalType: 'address', name: 'creator', type: 'address' },
          { internalType: 'bool', name: 'isListing', type: 'bool' },
          { internalType: 'bool', name: 'isERC1155', type: 'bool' },
          { internalType: 'address', name: 'tokenContract', type: 'address' },
          { internalType: 'uint256', name: 'tokenId', type: 'uint256' },
          { internalType: 'uint256', name: 'quantity', type: 'uint256' },
          { internalType: 'uint96', name: 'expiry', type: 'uint96' },
          { internalType: 'address', name: 'currency', type: 'address' },
          { internalType: 'uint256', name: 'pricePerToken', type: 'uint256' },
        ],
        internalType: 'struct ISequenceMarketStorage.Request',
        name: 'request',
        type: 'tuple',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'uint256[]', name: 'requestIds', type: 'uint256[]' },
      { internalType: 'uint256[]', name: 'quantities', type: 'uint256[]' },
    ],
    name: 'isRequestValidBatch',
    outputs: [
      { internalType: 'bool[]', name: 'valid', type: 'bool[]' },
      {
        components: [
          { internalType: 'address', name: 'creator', type: 'address' },
          { internalType: 'bool', name: 'isListing', type: 'bool' },
          { internalType: 'bool', name: 'isERC1155', type: 'bool' },
          { internalType: 'address', name: 'tokenContract', type: 'address' },
          { internalType: 'uint256', name: 'tokenId', type: 'uint256' },
          { internalType: 'uint256', name: 'quantity', type: 'uint256' },
          { internalType: 'uint96', name: 'expiry', type: 'uint96' },
          { internalType: 'address', name: 'currency', type: 'address' },
          { internalType: 'uint256', name: 'pricePerToken', type: 'uint256' },
        ],
        internalType: 'struct ISequenceMarketStorage.Request[]',
        name: 'requests',
        type: 'tuple[]',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'owner',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'renounceOwnership',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: 'tokenContract', type: 'address' },
      { internalType: 'address', name: 'recipient', type: 'address' },
      { internalType: 'uint96', name: 'fee', type: 'uint96' },
    ],
    name: 'setRoyaltyInfo',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: 'newOwner', type: 'address' }],
    name: 'transferOwnership',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
] as const;
